// SPDX-License-Identifier: BSD-3-Clause

//go:build amd64 && gc && !purego

package chacha20poly1305

import (
	"flag"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

// dropHeader splits generated assembly into lines minus avo's leading
// "Code generated by command: ..." line.
func dropHeader(s string) []string {
	lines := strings.Split(s, "\n")
	if len(lines) > 0 && strings.HasPrefix(lines[0], "// Code generated by command:") {
		return lines[1:]
	}
	return lines
}

var runRegenTests = flag.Bool("run-regen-tests", false,
	"run the avo regeneration test (needs the avo module in the module cache); always on when CI=true")

// TestRegenReproducible verifies that running the avo generator in _asm
// reproduces the checked-in chacha20poly1305_amd64.s exactly.
//
// Unlike tsasm/arm's equivalent this has no network dependency once the module
// cache is warm and needs no external tools beyond the Go toolchain: the
// generator is pure Go with its avo version pinned in _asm/go.mod. It is gated
// the same way anyway, for consistency with tsasm/arm and so a cold cache does
// not fail an offline build.
func TestRegenReproducible(t *testing.T) {
	if !*runRegenTests && os.Getenv("CI") != "true" {
		t.Skip("regen test is gated: pass --run-regen-tests or set CI=true")
	}

	const generated = "chacha20poly1305_amd64.s"
	want, err := os.ReadFile(generated)
	if err != nil {
		t.Fatal(err)
	}

	out := filepath.Join(t.TempDir(), generated)
	cmd := exec.Command("go", "run", ".", "-out", out, "-pkg", "chacha20poly1305")
	cmd.Dir = "_asm"
	// The generator loads the target package through go/packages to read the
	// signatures of the //go:noescape declarations, so it needs GOARCH=amd64.
	// This test only builds on amd64, so the ambient value is already correct;
	// pin it anyway so a GOARCH override in the environment cannot confuse it.
	cmd.Env = append(os.Environ(), "GOARCH=amd64")
	if b, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("regenerating: %v\n%s", err, b)
	}

	got, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}

	// avo's first line records the exact command it was invoked with, including
	// the -out path, so it necessarily differs when generating to a temporary
	// directory. Compare everything after it.
	gotLines := dropHeader(string(got))
	wantLines := dropHeader(string(want))
	if slices.Equal(gotLines, wantLines) {
		return
	}
	t.Errorf("%s is stale: regenerating produced %d lines, checked-in has %d",
		generated, len(gotLines), len(wantLines))
	shown := 0
	for i := 0; i < len(gotLines) && i < len(wantLines) && shown < 30; i++ {
		if gotLines[i] != wantLines[i] {
			t.Errorf("line %d:\n  got:  %s\n  want: %s", i+1, gotLines[i], wantLines[i])
			shown++
		}
	}
	t.Logf("run `cd tsasm/amd64/chacha20poly1305/_asm && go generate ./...` and commit the result")
}

// TestUpstreamProvenance guards the claim this package rests on: that the
// generated assembly is byte-for-byte what golang.org/x/crypto shipped before
// commit 7ee5970 deleted it. It checks the shape rather than a hash of the
// whole file, since the header comment names our own package path.
//
// If this fails, the generator has been edited and the provenance argument in
// README.md no longer holds as stated.
func TestUpstreamProvenance(t *testing.T) {
	b, err := os.ReadFile("chacha20poly1305_amd64.s")
	if err != nil {
		t.Fatal(err)
	}
	s := string(b)
	// Markers that exist only in the SSE half upstream removed.
	for _, want := range []string{
		"TEXT ·chacha20Poly1305Open(SB)",
		"TEXT ·chacha20Poly1305Seal(SB)",
		"openSSE128:",
		"sealSSETail:",
		"#define ROL8(R, T) PSHUFB \u00b7rol8<>(SB), R",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("generated asm is missing %q", want)
		}
	}
	if n := strings.Count(s, "\n"); n < 9000 {
		t.Errorf("generated asm has %d lines, expected ~9762; the SSE half may be missing", n)
	}
}
