// SPDX-License-Identifier: BSD-3-Clause

//go:build amd64 && gc && !purego

package chacha20poly1305

import (
	"flag"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"testing"
)

// dropHeader splits generated assembly into lines minus avo's leading
// "Code generated by command: ..." line.
func dropHeader(s string) []string {
	lines := strings.Split(s, "\n")
	if len(lines) > 0 && strings.HasPrefix(lines[0], "// Code generated by command:") {
		return lines[1:]
	}
	return lines
}

var runRegenTests = flag.Bool("run-regen-tests", false,
	"run the avo regeneration test (needs the avo module in the module cache); always on when CI=true")

/*
TestRegenReproducible verifies that running the avo generator in _asm reproduces the checked-in chacha20poly1305_amd64.s exactly.

Unlike tsasm/arm's equivalent this has no network dependency once the module cache is warm and needs no external tools beyond the Go toolchain: the generator is pure Go with its avo version pinned in _asm/go.mod. It is gated the same way anyway, for consistency with tsasm/arm and so a cold cache does not fail an offline build.
*/
func TestRegenReproducible(t *testing.T) {
	if !*runRegenTests && os.Getenv("CI") != "true" {
		t.Skip("regen test is gated: pass --run-regen-tests or set CI=true")
	}

	for _, tc := range []struct {
		name      string
		avx512    bool
		generated string
	}{
		{"ssse3", false, "chacha20poly1305_amd64.s"},
		{"avx512", true, "chacha20poly1305_avx512_amd64.s"},
	} {
		t.Run(tc.name, func(t *testing.T) { checkRegen(t, tc.avx512, tc.generated) })
	}
}

func checkRegen(t *testing.T, avx512 bool, generated string) {
	want, err := os.ReadFile(generated)
	if err != nil {
		t.Fatal(err)
	}

	out := filepath.Join(t.TempDir(), generated)
	args := []string{"run", ".", "-out", out, "-pkg", "chacha20poly1305"}
	if avx512 {
		args = append(args, "-avx512")
	}
	cmd := exec.Command("go", args...)
	cmd.Dir = "_asm"
	/*
		The generator loads the target package through go/packages to read the signatures of the //go:noescape declarations, so it needs GOARCH=amd64. This test only builds on amd64, so the ambient value is already correct; pin it anyway so a GOARCH override in the environment cannot confuse it.
	*/
	cmd.Env = append(os.Environ(), "GOARCH=amd64")
	if b, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("regenerating: %v\n%s", err, b)
	}

	got, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}

	// avo's first line records the exact command it was invoked with, including
	// the -out path, so it necessarily differs when generating to a temporary
	// directory. Compare everything after it.
	gotLines := dropHeader(string(got))
	wantLines := dropHeader(string(want))
	if slices.Equal(gotLines, wantLines) {
		return
	}
	t.Errorf("%s is stale: regenerating produced %d lines, checked-in has %d",
		generated, len(gotLines), len(wantLines))
	shown := 0
	for i := 0; i < len(gotLines) && i < len(wantLines) && shown < 30; i++ {
		if gotLines[i] != wantLines[i] {
			t.Errorf("line %d:\n  got:  %s\n  want: %s", i+1, gotLines[i], wantLines[i])
			shown++
		}
	}
	t.Logf("run `cd tsasm/amd64/chacha20poly1305/_asm && go generate ./...` and commit the result")
}

/*
TestUpstreamProvenance guards the claim this package rests on: that the generated assembly is byte-for-byte what golang.org/x/crypto shipped before commit 7ee5970 deleted it. It checks the shape rather than a hash of the whole file, since the header comment names our own package path.

If this fails, the generator has been edited and the provenance claim above no longer holds as stated.
*/
func TestUpstreamProvenance(t *testing.T) {
	b, err := os.ReadFile("chacha20poly1305_amd64.s")
	if err != nil {
		t.Fatal(err)
	}
	s := string(b)
	// Markers that exist only in the SSE half upstream removed.
	for _, want := range []string{
		"TEXT ·chacha20Poly1305Open(SB)",
		"TEXT ·chacha20Poly1305Seal(SB)",
		"openSSE128:",
		"sealSSETail:",
		"#define ROL8(R, T) PSHUFB \u00b7rol8<>(SB), R",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("generated asm is missing %q", want)
		}
	}
	// The AVX2 half is removed, so assert it is gone rather than merely unreachable.
	for _, unwanted := range []string{"useAVX2", "VPADDD", "VPXOR", "VPSHUFB", "VPALIGNR", "_AVX2:"} {
		if strings.Contains(s, unwanted) {
			t.Errorf("generated asm still contains %q from the AVX2 half", unwanted)
		}
	}
	if strings.Contains(s, "Y0") || strings.Contains(s, "Y15") {
		t.Error("generated asm still references YMM registers")
	}

	// Every constant a macro names must also be defined. avo cannot see inside a #define,
	// so one referenced only from a macro body is not emitted just because the macro is:
	// that links at GOAMD64=v1, where the #else branch is taken, and fails at v2.
	for _, name := range []string{"rol16", "rol8"} {
		named := strings.Contains(s, "\u00b7"+name+"<>(SB)")
		defined := strings.Contains(s, "GLOBL \u00b7"+name+"<>(SB)")
		if named && !defined {
			t.Errorf("generated asm names \u00b7%s<>(SB) in a macro but never defines it; "+
				"this links at GOAMD64=v1 and fails at v2", name)
		}
	}

	if n := strings.Count(s, "\n"); n < 4500 || n > 5500 {
		t.Errorf("generated asm has %d lines, expected ~5021 for the SSE-only kernel", n)
	}
}

/*
TestAVX512KernelIsContained asserts two things about the AVX-512 kernel, both of which a generator slip could break silently.

That it is really AVX-512: the entry points exist and the 512-bit register file and VPROLD are present. VPROLD is the reason this kernel is worth having, because it rotates in one instruction where the SSSE3 kernel needs shift-shift-or, so its absence would mean the rotate had quietly fallen back.

And that AVX-512 stays contained to this file. The SSSE3 kernel runs on CPUs with no AVX-512 at all, so a 512-bit instruction leaking into it is a SIGILL on exactly the hardware this package exists to serve. The tier machinery makes that a one-line mistake in the generator, and nothing else would catch it: every machine that can run the AVX-512 kernel can also run any instruction that leaked.
*/
func TestAVX512KernelIsContained(t *testing.T) {
	b, err := os.ReadFile("chacha20poly1305_avx512_amd64.s")
	if err != nil {
		t.Fatal(err)
	}
	s := string(b)

	for _, want := range []string{
		"TEXT ·chacha20Poly1305SealAVX512(SB)",
		"TEXT ·chacha20Poly1305OpenAVX512(SB)",
		"VPROLD",
		// Each entry point's own Requires line, which avo writes directly above its TEXT. Both name AVX512BW because both use VMOVDQU8 and KMOVQ under byte masks, and that is what AvailableAVX512 requires BW for.
		"// Requires: AVX, AVX512BW, AVX512F, BMI2, CMOV\nTEXT ·chacha20Poly1305SealAVX512(SB)",
		"// Requires: AVX, AVX512BW, AVX512F, BMI2, CMOV\nTEXT ·chacha20Poly1305OpenAVX512(SB)",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("AVX-512 kernel is missing %q", want)
		}
	}
	if n := len(regexp.MustCompile(`\bZ[0-9]+\b`).FindAllString(s, -1)); n < 500 {
		t.Errorf("AVX-512 kernel names 512-bit registers only %d times, expected ~2000; the vector half may have fallen back to 256-bit", n)
	}

	// The containment half. MULXQ is allowed to appear here and nowhere else for the same reason: it needs BMI2, which the SSSE3 kernel does not require.
	zmm := regexp.MustCompile(`\bZ[0-9]+\b`)
	for _, f := range []string{"chacha20poly1305_amd64.s"} {
		b, err := os.ReadFile(f)
		if err != nil {
			t.Fatal(err)
		}
		s := string(b)
		if zmm.MatchString(s) {
			t.Errorf("%s names a 512-bit register; it must run on CPUs without AVX-512", f)
		}
		for _, absent := range []string{"AVX512", "VPROLD", "MULXQ", "VPADDD"} {
			if strings.Contains(s, absent) {
				t.Errorf("%s contains %q, which is above its instruction-set floor", f, absent)
			}
		}
	}
}
